### ISSUE TITLE
Visual Studio 2013 crashes System.ArgumentNullException

### ISSUE THREAD

**Issue by markvantilburg** [madskristensen/ImageOptimizer#3]
I rightclick a folder with a number of subfolders (589 Files, 10 Folders) that contain multiple file types and choose optimize images;

```
An unhandled exception of type 'System.ArgumentNullException' occurred in mscorlib.dll

Additional information: File name cannot be null.
```

**Comment by madskristensen** [comment]
This should be fixed if you update to the latest version

**Comment by markvantilburg** [comment]
I have version 3.0.14 installed. Is there a newer version?

**Comment by markvantilburg** [comment]
Installed 3.0.15 from appveyor - still crashes. Any pointer on how to find the error that causes this?
